### ISSUE TITLE
No module dimp_alpha_065

### ISSUE THREAD

**Issue by fedorzh** [MasterBin-IIAU/AlphaRefine#2]
After following https://github.com/MasterBin-IIAU/AlphaRefine/tree/master/AlphaRefine_submit, I am getting this in the logs:
`ModuleNotFoundError: No module named 'dimp_alpha_065'`

**Comment by MasterBin-IIAU** [comment]
@fedorzh 
Hi, the possible reason is that you should modify https://github.com/MasterBin-IIAU/AlphaRefine/blob/46bec7318702090199a49306ff3d597c2fc140f9/AlphaRefine_submit/AlphaRefine/trackers.ini#L6 to the real path on your computer. Thanks

**Comment by fedorzh** [comment]
Ok, you are right, thank you. Now I am getting `ModuleNotFoundError: No module named 'pytracking'` though

**Comment by MasterBin-IIAU** [comment]
Hi, `ModuleNotFoundError: No module named 'pytracking'` may be caused by the environment variable problem. 
Have you added the real path of **AlphaRefine_submit** to your bashrc file? (as mentioned in README under AlphaRefine_submit) `export PYTHONPATH=<path_of_AlphaRefine_submit>:$PYTHONPATH`
After adding new environment variables, please run `source ~/.bashrc` to make the new variables effective. 
Then you should open a new terminal to run this project. It will load your newest environment variables.

**Comment by MasterBin-IIAU** [comment]
> And if I hack around that one, the following error is `THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1556653114079/work/aten/src/THC/THCGeneral.cpp line=51 error=38 : no CUDA-capable device is detected`
> 
> I think the package is missing a right setup.py file

Hi, could you tell me your detailed hardware and software types? (such as GPU types, CUDA version, and Pytorch version, etc)
Did you install the pytorch using our command provided in README?  `conda install pytorch==1.2.0 torchvision==0.4.0 cudatoolkit=10.0 -c pytorch`

**Comment by fedorzh** [comment]
`Python 3.7.9`
`Cuda compilation tools, release 10.0, V10.0.130`
1 GPU `Tesla V100`
Pytorch was installed beforehand, as I need to test another tracker as well, version is `1.1.0`, torchvision is `0.3.0`

**Comment by MasterBin-IIAU** [comment]
> `Python 3.7.9`
> `Cuda compilation tools, release 10.0, V10.0.130`
> 1 GPU `Tesla V100`
> Pytorch was installed beforehand, as I need to test another tracker as well, version is `1.1.0`, torchvision is `0.3.0`

Hi, I think there might be the following possible reasons for this problem.

- Your driver for GPU is broken. Please run `nvidia-smi` to check it.
- There exist some conflict between your system's CUDA version and your pytorch version. I strongly suggest to temporally uninstall pytorch and torchvision in your current environment, then install pytorch1.1.0 using the following command. `conda install pytorch==1.1.0 torchvision==0.3.0 cudatoolkit=10.0 -c pytorch`

**Comment by fedorzh** [comment]
Well, I run Ocean tracker without problems on this driver and the same Anaconda environment.
`nvidia-smi` shows all good.

**Comment by fedorzh** [comment]
Also, I was able to run this AlphaRef tracker from an external python file, not through `exp.sh`, all works fine. But that doesn't run the VOT2020 evaluation

**Comment by MasterBin-IIAU** [comment]
Ok, is the problem still be no `CUDA-capable device is detected` now? 
I think if AlphaRefine can be run normally without vot-toolkit, `CUDA-capable device is detected`  problem should not exist now.

**Comment by fedorzh** [comment]
no the problem still exists if i run the toolkit way but does not exist if i run directly

**Comment by MasterBin-IIAU** [comment]
It is weird. I don't figure out why it happens. I'm sorry.
But since our code can be run normally without using vot-toolkit,  it seems that the problem is not about AlphaRefine itself. 
So I guess this issue could be closed because the problem with AlphaRefine has been solved.
